### ISSUE TITLE
Cookie not working

### ISSUE THREAD

**Issue by Q1984** [horizon3ai/vcenter_saml_login#7]
Hello!

The script reports Successfuly obtained Administrator cookie for .... but when I paste the value in the corresponding field the auth not working, just throws back to login screen.
As I check its working with vcenter 6.x but not success in vcenter 7.0.3.

Any idea?
Thx!

**Comment by scopedsecurity** [comment]
If a cookie is obtained successfully, I would ensure that you are correctly adding the cookie via the developer tab with the correct 'path' set to '/ui' and then making sure you browse directly to https://<host>/ui (don't just refresh). Let me know if you have that down, otherwise possibly inspect the request / response when you do browse to the correct URL and see if there are any out of place responses.
